# -*- coding: utf-8 -*-
"""greetingporbably.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpWECKQq6Ve489sBWTBn1tO8kPDDQJ9v
"""

import streamlit as st
st.title("👋 مرحبا بكم في موقعنا الاول باستخدام ستريم ليت")
name=st.text_input("ما هو اسمك ؟ 👋")
if name:
    st.write("نورت الموقع",name,"مرحباً بك يا")
    st.balloons()